# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest
jobs:
  - job: buildAndPushImageJob
    displayName: Build and push container image

    steps:
    - script: echo Hello, world!
      displayName: 'Run a one-line script'

    - script: |
        echo Add other tasks to build, test, and deploy your project.
        echo See https://aka.ms/yaml
      displayName: 'Run a multi-line script'

    - pwsh: |
        $url = "$($env:SYSTEM_TEAMFOUNDATIONCOLLECTIONURI)$env:SYSTEM_TEAMPROJECTID/_apis/build/definitions/$($env:SYSTEM_DEFINITIONID)?api-version=4.1-preview"
        Write-Host "URL: $url"
        $pipeline = Invoke-RestMethod -Uri $url -Headers @{
          Authorization = "Bearer $env:NPM_TOKEN"
        }
        Write-Host "Pipeline = $($pipeline | ConvertTo-Json -Depth 100)"
      env:
        NPM_TOKEN: $(System.AccessToken)
      displayName: 'Set an env var'

    - pwsh: |
        Write-Host "Token = " $env:NPM_TOKEN
        ./scripts/buildAndPushContainerImage.ps1 `
      env:
        NPM_TOKEN: $(System.AccessToken)
      displayName: Docker build
