# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest
jobs:
  - job: buildAndPushImageJob
    displayName: Build and push container image

    steps:
    - script: echo Hello, world!
      displayName: 'Run a one-line script'

    - script: |
        echo Add other tasks to build, test, and deploy your project.
        echo See https://aka.ms/yaml
      displayName: 'Run a multi-line script'

    - pwsh: |
        ./scripts/buildAndPushContainerImage.ps1 `
          -containerRepository Project2 `
          -branchName Main `
          -version 1.0.0 `
          -action Build
      env:
        NPM_TOKEN: $(System.AccessToken)
      displayName: Docker build
